/* Editable content for the site. App records live in data.js. */
window.FX = {
  github: 'polyphase123',

  /* Repos deliberately left out of the list (duplicates or dead links).
     The live GitHub check skips these so they don't come back as "new". */
  skip: ['HVDC', 'ROCOF', 'systemloss', 'garin', 'geatrack', 'geatracker', 'fork', 'mastermap', 'reliability', 'iran',
         'pshfranz', 'IEEE30bus', 'IEEE30busv2', 'newton', 'NMmap', 'global.github.io', 'barney', 'GEAmap', 'GEAquartro',
         'GEAonefour', 'fx-site'],

  cats: [
    { id: 'reg',  shape: 'sq',  nm: { en: ['REGULATION', '+', 'POLICY'], fil: ['REGULASYON', '+', 'POLISIYA'] },
      lead: { en: 'ERC rules, Green Energy Auctions, net-metering and the paperwork behind them.', fil: 'Mga patakaran ng ERC, Green Energy Auction, net-metering at ang mga papeles sa likod nito.' } },
    { id: 'grid', shape: 'ci',  nm: { en: ['GRID', '+', 'POWER'], fil: ['GRID', '+', 'KURYENTE'] },
      lead: { en: 'Power flow, protection, faults, grounding and the NGCP grid in real time.', fil: 'Power flow, proteksiyon, fault, grounding at ang NGCP grid.' } },
    { id: 're',   shape: 'tri', nm: { en: ['SOLAR', 'WIND', '+ STORAGE'], fil: ['ARAW', 'HANGIN', '+ BATERYA'] },
      lead: { en: 'DER and net-metering calculators, PV and BESS sizing, wind and wave.', fil: 'Calculator para sa DER at net-metering, sukat ng PV at BESS, hangin at alon.' } },
    { id: 'nuke', shape: 'x',   nm: { en: ['NUCLEAR'], fil: ['NUKLEYAR'] },
      lead: { en: 'Reactor simulators, fuel cycle and the economics of nuclear for the Philippines.', fil: 'Simulator ng reactor, fuel cycle at ang ekonomiya ng nukleyar para sa Pilipinas.' } },
    { id: 'mkt',  shape: 'dia', nm: { en: ['MARKETS', '+', 'MONEY'], fil: ['MERKADO', '+', 'PERA'] },
      lead: { en: 'Tariffs, WESM hedging, fuel prices, taxes and the national budget.', fil: 'Taripa, WESM hedging, presyo ng gasolina, buwis at pambansang badyet.' } },
    { id: 'play', shape: 'ring', nm: { en: ['PLAY-', 'GROUND'], fil: ['PALARUAN'] },
      lead: { en: 'Heroes, moon landings, air traffic control, football and everything else.', fil: 'Mga bayani, paglapag sa buwan, air traffic control, football at iba pa.' } },
  ],
  newCat: { id: 'new', shape: 'star', nm: { en: ['FRESH', 'OFF THE', 'BENCH'], fil: ['BAGO', 'SA', 'MESA'] },
    lead: { en: 'New on GitHub since this page was last edited. Not sorted into a drawer yet.', fil: 'Bago sa GitHub mula nang huling i-edit ang page na ito. Hindi pa naisasaayos.' } },

  /* Featured spotlight */
  spot: [
    { r: 'tx', why: { en: 'Turns a 35-page ERC resolution into chapters, deadline calculators, pre-filing checklists and a 50-question compliance test, with a chatbot that cites the exact provision.', fil: 'Ginagawang mga kabanata, deadline calculator, checklist at 50-tanong na pagsusulit ang 35-pahinang resolusyon ng ERC, may chatbot pang nagbabanggit ng eksaktong probisyon.' } },
    { r: 'supertariffcalculator', why: { en: 'Stack GEA rounds, PEP 2050 scenarios or a revived Bataan plant on the 2026 grid and watch the blended tariff, RE share and CO₂ move.', fil: 'Idagdag ang mga GEA round, PEP 2050 o muling binuhay na Bataan sa 2026 grid at panoorin ang paggalaw ng taripa, RE share at CO₂.' } },
    { r: 'solarbesspowerplant', why: { en: 'Lay out a utility solar and battery plant block by block, then test it against grid voltage and frequency ride-through.', fil: 'Iayos ang solar at battery plant isa-isang block, saka subukan sa voltage at frequency ride-through ng grid.' } },
    { r: 'HVDCngcp', why: { en: 'The Leyte–Luzon and Mindanao–Visayas HVDC links explained, with a what-if mode for HVAC alternatives.', fil: 'Paliwanag sa Leyte–Luzon at Mindanao–Visayas HVDC, may what-if para sa HVAC na alternatibo.' } },
    { r: 'nukefin', why: { en: 'A financial model for nuclear in the Philippines: capex, financing and tariff impact in one screen.', fil: 'Financial model para sa nukleyar sa Pilipinas: capex, financing at epekto sa taripa sa iisang screen.' } },
    { r: 'bayani', why: { en: 'A map of 60+ national heroes: where they were born, where they died and how. Built as a tribute.', fil: 'Mapa ng 60+ pambansang bayani: saan sila ipinanganak, saan namatay at paano. Isang pagpupugay.' } },
  ],

  /* #fxitobias posts. Drop an .mp4 at the "video" path and the card plays it. */
  notes: [
    { when: 'Sep 2026', stat: '921 months', video: 'videos/heat-spiral.mp4', t: 'Metro Manila Heat Spiral',
      b: { en: '77 years of monthly peak temperatures from PAGASA records, animated and turned into sound.', fil: '77 taon ng pinakamataas na buwanang temperatura mula sa PAGASA, gumagalaw at may tunog.' },
      href: 'https://www.linkedin.com/search/results/content/?keywords=%23fxitobias', kind: 'post' },
    { when: 'Sep 2026', stat: '6,433 impressions', video: 'videos/meralco-spiral.mp4', t: 'Meralco Rate Spiral',
      b: { en: '213 months of unbundled residential tariffs laid over climate data, 2009 to 2026.', fil: '213 buwan ng residential na taripa ng Meralco kasama ang datos ng klima, 2009 hanggang 2026.' },
      href: 'https://www.linkedin.com/search/results/content/?keywords=%23fxitobias', kind: 'post' },
    { when: 'Jul 2026', stat: 'web app', r: 'bayani', t: 'Bayani',
      b: { en: 'A small tribute to our national heroes: where they were born, where they died and how.', fil: 'Munting pagpupugay sa ating mga bayani: saan sila ipinanganak, saan namatay at paano.' } },
    { when: 'Jul 2026', stat: 'web app', r: 'supertariffcalculator', t: 'Super Tariff Calculator',
      b: { en: 'What GEA, nuclear and new capacity do to the price of a kilowatt-hour.', fil: 'Ano ang epekto ng GEA, nukleyar at bagong planta sa presyo ng isang kilowatt-hour.' } },
    { when: 'Jun 2026', stat: 'web app', r: 'tx', t: 'GridConnect//18',
      b: { en: 'ERC Resolution No. 18 made usable: AI chatbot, milestone calculator and a 50-question quiz.', fil: 'Mas madaling gamitin ang ERC Resolution No. 18: AI chatbot, milestone calculator at 50-tanong na quiz.' } },
    { when: 'Jun 2026', stat: 'web app', r: 'mspectrum', t: 'MSpectrum Calculator',
      b: { en: 'Decoding Meralco MSpectrum’s no-upfront net-metering offer.', fil: 'Pagsusuri sa alok ng Meralco MSpectrum na walang paunang bayad.' } },
  ],

  cases: [
    { r: 'tx', t: 'GridConnect//18', meta: 'ERC Resolution No. 18 s.2026 · Jun 2026',
      rows: {
        en: [
          ['THE PROBLEM', 'On June 8, 2026 the ERC adopted new rules for point-to-point lines, Associated Transmission Projects and Priority Projects. Generation companies, TRANSCO and the grid operator all needed to know their deadlines and filings, and the answer sat inside 35 pages of legal text.'],
          ['WHAT I BUILT', 'A handbook in eleven chapters, from objectives to fines and penalties. A milestone calculator works backward from a target commercial operations date. Pre-filing checklists cover the six annexes, and a cost-takeover simulator estimates asset values.'],
          ['THE DETAIL', 'The chatbot answers plain questions such as “who takes over the facilities?” and cites the provision it relied on. A bank of 100 Q&A items and a 50-question test let a team check what it actually understood.'],
          ['WHY IT MATTERS', 'A missed regulatory milestone can strand a generation asset. Here the rules become dates and checklists a project team can act on.'],
        ],
        fil: [
          ['ANG PROBLEMA', 'Noong Hunyo 8, 2026, inaprubahan ng ERC ang bagong patakaran para sa point-to-point lines, ATP at Priority Projects. Kailangang malaman ng mga GenCo, TRANSCO at grid operator ang kanilang deadline at dokumento, pero nakabaon ito sa 35 pahina ng legal na teksto.'],
          ['ANG GINAWA KO', 'Handbook na may labing-isang kabanata. May milestone calculator na nagbibilang pabalik mula sa target na COD, checklist para sa anim na annex, at simulator para sa halaga ng asset na ita-takeover.'],
          ['ANG DETALYE', 'Sinasagot ng chatbot ang simpleng tanong gaya ng “sino ang magte-takeover ng pasilidad?” at binabanggit ang probisyon. May 100 Q&A at 50-tanong na pagsusulit para masukat ng team ang naintindihan nila.'],
          ['BAKIT MAHALAGA', 'Ang isang hindi naabot na milestone ay puwedeng mag-iwan ng planta na hindi makakonekta. Dito, nagiging petsa at checklist ang patakaran.'],
        ] } },
    { r: 'supertariffcalculator', t: 'Super Tariff Calculator', meta: 'v3.5.0 · Jul 2026',
      rows: {
        en: [
          ['THE PROBLEM', 'Debates about the Green Energy Auction and nuclear power often stop at “it will raise prices” or “it will lower prices,” with no numbers on the table.'],
          ['WHAT I BUILT', 'A scenario engine on the 2026 committed-plant baseline for the national grid or for Luzon, Visayas and Mindanao separately. Presets cover GEA 1 to 5, the PEP 2050 reference and clean-energy cases, a revived 621 MW Bataan plant, and 1.2 GW of nuclear by 2032. A custom builder adds any plant type unit by unit.'],
          ['THE DETAIL', 'Demand growth, RE cost decline, curtailment risk and grid upgrades are all adjustable. Outputs include the blended tariff, RE share, WESM marginal price, system inertia, N-1 stability and annual CO₂.'],
          ['WHY IT MATTERS', 'Policy talk gets grounded in pesos per kilowatt-hour, and anyone can test their own assumptions in the browser.'],
        ],
        fil: [
          ['ANG PROBLEMA', 'Madalas nauuwi sa “tataas ang presyo” o “bababa ang presyo” ang usapan tungkol sa GEA at nukleyar, nang walang numerong pinagbabatayan.'],
          ['ANG GINAWA KO', 'Scenario engine batay sa 2026 committed plants para sa buong bansa o sa Luzon, Visayas at Mindanao. May preset para sa GEA 1 hanggang 5, PEP 2050, muling binuhay na 621 MW Bataan, at 1.2 GW nukleyar pagsapit ng 2032. Puwede ring magdagdag ng sariling planta.'],
          ['ANG DETALYE', 'Naaayos ang paglago ng demand, pagbaba ng gastos ng RE, curtailment at grid upgrade. Lumalabas ang blended tariff, RE share, presyo sa WESM, inertia, N-1 at CO₂ bawat taon.'],
          ['BAKIT MAHALAGA', 'Nagkakaroon ng piso-kada-kilowatt-hour na batayan ang usapang polisiya, at kahit sino ay puwedeng sumubok ng sariling palagay.'],
        ] } },
    { r: 'mspectrum', t: 'MSpectrum Solar Calculator', meta: 'Meralco May 2026 rates · Jun 2026',
      rows: {
        en: [
          ['THE PROBLEM', 'Meralco’s MSpectrum offers rooftop solar with no upfront payment, but the price depends on promo discounts, a rate floor, net-metering credits and the season. Homeowners can’t tell whether it saves them money.'],
          ['WHAT I BUILT', 'A calculator for both plans, Solar Savings and Solar Subscription, priced on the May 2026 Meralco rate schedule. It handles residential and small commercial customers, dry and wet seasons, Peak Off-Peak and an optional 5 kWh battery.'],
          ['THE DETAIL', 'The Savings Plan rate is the blended rate less ₱3.00/kWh in years 1–3 and less ₱2.00/kWh after that, never below ₱11.50/kWh. With the app’s sample inputs (a ₱8,993 bill and a 5 kWp system) it estimates about ₱1,665 a month in savings.'],
          ['WHY IT MATTERS', 'A homeowner can see the full bill before signing: the Meralco bill, the MSpectrum bill and the total.'],
        ],
        fil: [
          ['ANG PROBLEMA', 'Walang paunang bayad ang solar ng MSpectrum, pero nakadepende ang presyo sa promo, rate floor, net-metering at panahon. Hindi malaman ng may-bahay kung makakatipid ba talaga sila.'],
          ['ANG GINAWA KO', 'Calculator para sa Solar Savings at Solar Subscription Plan gamit ang Mayo 2026 na rate ng Meralco. Kasama ang residential at maliit na negosyo, tag-araw at tag-ulan, Peak Off-Peak at opsiyonal na 5 kWh na baterya.'],
          ['ANG DETALYE', 'Sa Savings Plan, blended rate bawas ₱3.00/kWh sa taon 1–3 at bawas ₱2.00/kWh pagkatapos, hindi bababa sa ₱11.50/kWh. Sa sample ng app (₱8,993 na bill, 5 kWp) mga ₱1,665 kada buwan ang tipid.'],
          ['BAKIT MAHALAGA', 'Nakikita ng may-bahay ang buong bill bago pumirma: ang bill ng Meralco, ang bill ng MSpectrum at ang kabuuan.'],
        ] } },
  ],

  services: [
    { t: { en: 'Distribution impact studies', fil: 'Distribution impact study' },
      b: { en: 'Load flow, short circuit and protection studies for embedded solar, wind and storage, in ETAP. Done for ADB-funded projects.', fil: 'Load flow, short circuit at proteksiyon para sa solar, hangin at storage, gamit ang ETAP. Nagawa na para sa mga proyektong pinondohan ng ADB.' } },
    { t: { en: 'Financial models', fil: 'Financial model' },
      b: { en: 'Tariff impact, PSA benchmarking, GEA bid pricing, BESS and solar project returns.', fil: 'Epekto sa taripa, PSA benchmarking, presyo ng GEA bid, kita ng BESS at solar.' } },
    { t: { en: 'Interactive tools and dashboards', fil: 'Interactive na tool at dashboard' },
      b: { en: 'Turn a regulation, dataset or model into a web app your team or the public can use. 100+ shipped.', fil: 'Gawing web app ang regulasyon, datos o model para sa team o publiko. Mahigit 100 na ang nagawa.' } } ,
    { t: { en: 'Substation and protection design', fil: 'Disenyo ng substation at proteksiyon' },
      b: { en: 'Grounding to IEEE 80, arc flash to IEEE 1584, protection coordination and commissioning.', fil: 'Grounding ayon sa IEEE 80, arc flash ayon sa IEEE 1584, koordinasyon ng proteksiyon at commissioning.' } },
    { t: { en: 'Training and explainers', fil: 'Pagsasanay at paliwanag' },
      b: { en: 'Quizzes, simulators and briefings on EPIRA, WESM and grid basics for teams and students.', fil: 'Quiz, simulator at briefing tungkol sa EPIRA, WESM at grid para sa mga team at estudyante.' } },
  ],

  /* Tag rules: tag -> regex tested against repo + title + description */
  tags: [
    ['ERC', /\bERC\b|resolution|EPIRA|COC|tx$|PSPtoolkit|system loss|price cap/i],
    ['GEA', /\bGEA|green energy auction|indexation/i],
    ['Net-metering', /net-meter|NMcomparator|NMmapping/i],
    ['Meralco', /meralco|mspectrum|ILP/i],
    ['WESM', /WESM|hedg|N-1/i],
    ['NGCP', /NGCP|GOMP|GridIntel|grid crisis|HVDC/i],
    ['Solar', /solar|PV|shading|p-n junction/i],
    ['Wind', /wind|WTG|OSW|offshore/i],
    ['Storage', /BESS|battery/i],
    ['DER', /\bDER\b|microgrid/i],
    ['Nuclear', /nuclear|reactor|uranium|AP1000|CANDU|radiation|BNPP/i],
    ['Protection', /relay|fault|arc flash|breaker|grounding|X\/R|harmonic|damper/i],
    ['Simulator', /simulat|digital twin|lab\b/i],
    ['Map', /\bmap\b|explorer|tracker/i],
    ['Calculator', /calculat|estimat|sizing/i],
    ['Quiz', /quiz|exam|reviewer/i],
    ['History', /hero|rizal|apollo|bataan|malampaya/i],
  ],
};

/* Interface text. Keys match data-i18n attributes. */
window.FX_I18N = {
  en: {
    'nav.work': '[WORK]', 'nav.cases': '[CASES]', 'nav.hire': '[HIRE]', 'nav.about': '[ABOUT]',
    'hero.roles': '<span>[PROFESSIONAL ELECTRICAL ENGINEER]</span> <span>[INNOVATOR]</span>',
    'hero.note': '<b class="nApps">{n}</b> live web apps on the Philippine grid, markets and policy.',
    'hum.off': '[HUM: OFF]', 'hum.on': '[HUM: ON]',
    'stat.apps': 'live apps', 'stat.pace': 'apps a week, on average', 'stat.span': 'months of building',
    'stat.views': 'impressions on the top post', 'stat.followers': 'LinkedIn followers', 'stat.gea': 'GEA rounds worked on',
    'work.sub': 'Every app is live on GitHub Pages. Start with a favorite, pick a drawer, or search all of them.',
    'work.searchAll': 'SEARCH ALL APPS', 'work.go': '[GO]', 'work.random': '[RANDOM]',
    'spot.open': 'OPEN THE APP ↗', 'spot.code': 'source',
    'cat.apps': 'apps', 'all.title': 'ALL APPS', 'all.lead': 'Every project, favorites first, then newest.',
    'tag.lead': 'Every app tagged “{t}”.', 'filter.drawer': 'FILTER THIS DRAWER', 'filter.all': 'FILTER ALL APPS',
    'empty': 'Nothing here matches “{q}”. Try a shorter word.',
    'app.open': 'open app ↗', 'app.code': 'source', 'app.new': 'NEW',
    'tl.title': '[ONE DOT = ONE APP]', 'tl.sub': '{n} apps from {a} to {b}. Tap a dot to see it.',
    'notes.title': 'LATELY ON', 'notes.sub': 'Recent posts from LinkedIn.', 'notes.post': 'SEE THE POST', 'notes.app': 'OPEN THE APP',
    'cases.sub': 'Three apps, and the thinking behind them.', 'cases.open': '[OPEN THE APP ↗]',
    'hire.sub': 'Open to work in Metro Manila, hybrid. Here is what I can take on.',
    'hire.contact': 'The fastest way to reach me is a LinkedIn message. Tell me the problem, the deadline and who it’s for.',
    'hire.li': '[MESSAGE ON LINKEDIN ↗]',
    'about.hey': '— HEY.', 'about.base': 'BASE', 'about.field': 'FIELD', 'about.school': 'SCHOOL',
    'about.fieldV': 'Power systems, energy regulation, quant finance', 'about.statusV': 'Open to work · hybrid',
    'about.my': 'MY NAME IS',
    'about.p1': 'I’m a Professional Electrical Engineer, and most of my career has been in service of the Philippine Government and the Filipino people. I worked on Green Energy Auction rounds 1 to 7, the 2025 amended net-metering rules, and the rules for DER, energy storage, EV charging and microgrids.',
    'about.p2': 'Before that I spent seven years at the National Electrification Administration designing substations and rural grids, ran Meralco’s AMI smart grid in Ortigas, and consulted for ADB, the World Bank and NEDA on PPP projects and the Cebu BRT.',
    'about.p3': 'After hours I turn regulations and grid physics into small web apps anyone can click through. I tag every one of them <a class="tag" href="https://www.linkedin.com/search/results/content/?keywords=%23fxitobias" target="_blank" rel="noopener">#fxitobias</a>.',
    'foot': 'Inked in Metro Manila. Coded with Claude.',
    'blurbNote': '',
  },
  fil: {
    'nav.work': '[GAWA]', 'nav.cases': '[KASO]', 'nav.hire': '[KUNIN AKO]', 'nav.about': '[AKO]',
    'hero.roles': '<span>[PROPESYONAL NA INHINYERONG ELEKTRIKAL]</span> <span>[INOBADOR]</span>',
    'hero.note': '<b class="nApps">{n}</b> web app tungkol sa grid, merkado at polisiya ng kuryente sa Pilipinas.',
    'hum.off': '[UGONG: PATAY]', 'hum.on': '[UGONG: BUKAS]',
    'stat.apps': 'live na app', 'stat.pace': 'app kada linggo, karaniwan', 'stat.span': 'buwan ng paggawa',
    'stat.views': 'impressions sa pinakasikat na post', 'stat.followers': 'follower sa LinkedIn', 'stat.gea': 'GEA round na hinawakan',
    'work.sub': 'Live sa GitHub Pages ang bawat app. Magsimula sa paborito, pumili ng drawer, o hanapin lahat.',
    'work.searchAll': 'HANAPIN SA LAHAT NG APP', 'work.go': '[HANAP]', 'work.random': '[KAHIT ANO]',
    'spot.open': 'BUKSAN ANG APP ↗', 'spot.code': 'source',
    'cat.apps': 'app', 'all.title': 'LAHAT NG APP', 'all.lead': 'Lahat ng proyekto, una ang paborito, saka ang pinakabago.',
    'tag.lead': 'Lahat ng app na may tag na “{t}”.', 'filter.drawer': 'SALAIN ANG DRAWER', 'filter.all': 'SALAIN ANG LAHAT',
    'empty': 'Walang tugma sa “{q}”. Subukan ang mas maikling salita.',
    'app.open': 'buksan ↗', 'app.code': 'source', 'app.new': 'BAGO',
    'tl.title': '[ISANG TULDOK = ISANG APP]', 'tl.sub': '{n} app mula {a} hanggang {b}. Pindutin ang tuldok.',
    'notes.title': 'BAGO SA', 'notes.sub': 'Mga bagong post sa LinkedIn.', 'notes.post': 'TINGNAN ANG POST', 'notes.app': 'BUKSAN ANG APP',
    'cases.sub': 'Tatlong app at ang pag-iisip sa likod nila.', 'cases.open': '[BUKSAN ANG APP ↗]',
    'hire.sub': 'Bukas sa trabaho sa Metro Manila, hybrid. Ito ang kaya kong gawin.',
    'hire.contact': 'Pinakamabilis akong maabot sa LinkedIn message. Sabihin ang problema, ang deadline at para kanino.',
    'hire.li': '[MAG-MESSAGE SA LINKEDIN ↗]',
    'about.hey': '— KUMUSTA.', 'about.base': 'LUGAR', 'about.field': 'LARANGAN', 'about.school': 'PAARALAN',
    'about.fieldV': 'Power systems, regulasyon ng enerhiya, quant finance', 'about.statusV': 'Bukas sa trabaho · hybrid',
    'about.my': 'AKO SI',
    'about.p1': 'Isa akong Professional Electrical Engineer, at ang malaking bahagi ng aking karera ay inilaan ko sa paglilingkod sa Pamahalaan ng Pilipinas at sa sambayanang Pilipino. Hinawakan ko ang Green Energy Auction round 1 hanggang 7, ang 2025 amended net-metering rules, at ang mga patakaran para sa DER, energy storage, EV charging at microgrid.',
    'about.p2': 'Bago iyon, pitong taon ako sa National Electrification Administration na nagdidisenyo ng substation at rural na grid, humawak ng AMI smart grid ng Meralco sa Ortigas, at naging consultant ng ADB, World Bank at NEDA para sa mga PPP project at Cebu BRT.',
    'about.p3': 'Pagkatapos ng trabaho, ginagawa kong web app ang mga regulasyon at physics ng grid para madaling gamitin ng kahit sino. Lahat sila ay may tag na <a class="tag" href="https://www.linkedin.com/search/results/content/?keywords=%23fxitobias" target="_blank" rel="noopener">#fxitobias</a>.',
    'foot': 'Iginuhit sa Metro Manila. Kinode kasama si Claude.',
  },
};
